export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SERVER_RESPONSE_ERROR =
  "LOGIN_USER_SERVER_RESPONSE_ERROR";
export const LOGIN_USER_SERVER_RESPONSE_SUCCESS =
  "LOGIN_USER_SERVER_RESPONSE_SUCCESS";
  export const VALIDATE_USER_SERVER_RESPONSE_ERROR = 'VALIDATE_USER_SERVER_RESPONSE_ERROR';
  export const VALIDATE_USER_SERVER_RESPONSE_SUCCESS = 'VALIDATE_USER_SERVER_RESPONSE_SUCCESS';

export const SIGNUP_USER = "SIGNUP_USER";
export const SIGNUP_USER_SERVER_RESPONSE_ERROR =
  "SIGNUP_USER_SERVER_RESPONSE_ERROR";
export const SIGNUP_USER_SERVER_RESPONSE_SUCCESS =
  "SIGNUP_USER_SERVER_RESPONSE_SUCCESS";

export const CREATE_TIMESHEET = "CREATE_TIMESHEET";
export const CREATE_TIMESHEET_WORKINGHOUR = "CREATE_TIMESHEET_WORKINGHOUR";


export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_USER_SERVER_RESPONSE_SUCCESS =
  "LOGOUT_USER_SERVER_RESPONSE_SUCCESS";
export const LOGOUT_USER_SERVER_REPONSE_ERROR =
  "LOGOUT_USER_SERVER_REPONSE_ERROR";

export const IS_USER_LOGGED_IN = "IS_USER_LOGGED_IN";
export const VALIDATE_TOKEN_SERVER_RESPONSE_SUCCESS =
  "VALIDATE_TOKEN_SERVER_RESPONSE_SUCCESS";
export const VALIDATE_TOKEN_SERVER_REPONSE_ERROR =
  "VALIDATE_TOKEN_SERVER_REPONSE_ERROR";

export const SIGNUP_SAVE_DATABASE = "SIGNUP_SAVE_DATABASE";
export const SIGNUP_SAVE_DATABASE_SERVER_RESPONSE_SUCCESS =
  "SIGNUP_SAVE_DATABASE_SERVER_RESPONSE_SUCCESS";
export const SIGNUP_SAVE_DATABASE_SERVER_RESPONSE_ERROR =
  "SIGNUP_SAVE_DATABASE_SERVER_RESPONSE_ERROR";

export const EMPLOYEE_SAVE_DATABASE = "EMPLOYEE_SAVE_DATABASE";
export const EMPLOYEE_SAVE_DATABASE_SERVER_RESPONSE_SUCCESS =
  "EMPLOYEE_SAVE_DATABASE_SERVER_RESPONSE_SUCCESS";
export const EMPLOYEE_SAVE_DATABASE_SERVER_RESPONSE_ERROR =
  "EMPLOYEE_SAVE_DATABASE_SERVER_RESPONSE_ERROR";

export const GET_EMPLOYEE_LIST = "GET_EMPLOYEE_LIST";
export const GET_EMPLOYEE_LIST_SUCCESS_RESPONSE =
  "GET_EMPLOYEE_LIST_SUCCESS_RESPONSE";
export const GET_UPDATED_EMPLOYEE_LIST_SUCCESS_RESPONSE =
  "GET_UPDATED_EMPLOYEE_LIST_SUCCESS_RESPONSE";
export const GET_EMPLOYEE_LIST_ERROR_RESPONSE =
  "GET_EMPLOYEE_LIST_ERROR_RESPONSE";
