export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SERVER_RESPONSE_ERROR = 'LOGIN_USER_SERVER_RESPONSE_ERROR';
export const LOGIN_USER_SERVER_RESPONSE_SUCCESS = 'LOGIN_USER_SERVER_RESPONSE_SUCCESS';


export const CREATE_TIMESHEET = "CREATE_TIMESHEET";
export const CREATE_TIMESHEET_WORKINGHOUR = "CREATE_TIMESHEET_WORKINGHOUR";
export const CREATE_TIMESHEET_SAVE_WORKINGHOUR = "CREATE_TIMESHEET_SAVE_WORKINGHOUR";


export const LIST_EMPLOYEE_DETAILS = "LIST_EMPLOYEE_DETAILS";
export const LIST_EMPLOYEE_DETAILS_SERVER_RESPONSE_SUCESS = "LIST_EMPLOYEE_DETAILS_RESPONSE_SUCESS";
export const LIST_EMPLOYEE_DETAILS_SERVER__RESPONSE_ERROR = "LIST_EMPLOYEE_DETAILS_RESPONSE_ERROR";

